### ISSUE TITLE
Release stray output patch?

### ISSUE THREAD

**Issue by simonrepp** [alethiophile/qtoml#2]
Hi,

I am evaluating (among others) TOML benchmarks at https://github.com/eno-lang/benchmarks and experimentally tried out your library when I noticed stray debug output filling my console - I've already seen that you have fixed the issue but it took me a while to figure out why I was still getting stray output then, although you had already fixed this weeks ago.

Bottom line, you might want to consider doing a patch release for this, I'd certainly be happy about it :)
Thanks for providing this! :+1: 

Best, Simon

**Comment by alethiophile** [comment]
You're right, that's a good idea. 0.2.3 is now out with that fix.

**Comment by simonrepp** [comment]
That was fast :) thanks a lot!
