### ISSUE TITLE
Problems in dealing with scientific notation

### ISSUE THREAD

**Issue by ziotom78** [alethiophile/qtoml#4]
I'm running Miniconda 3.6.7 on a Linux machine. The following program works as expected:

```python
import qtoml

string = qtoml.dumps({'a': 1.0})
print('Encoded TOML: ', string)
qtoml.loads(string)
```

However, changing the value of `a` from 1.0 to 1.0e-9 makes qtoml crash:

```python
import qtoml

string = qtoml.dumps({'a': 1.0e-9})
print('Encoded TOML: ', string)
qtoml.loads(string)
```

The error is the following:
```
Encoded TOML:  a = 1e-09

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    qtoml.loads(string)
  File "/HOME/miniconda3/lib/python3.6/site-packages/qtoml/decoder.py", line 514, in loads
    (kl, v), p = parse_pair(p)
  File "/HOME/miniconda3/lib/python3.6/site-packages/qtoml/decoder.py", line 428, in parse_pair
    v, p = parse_value(p)
  File "/HOME/miniconda3/lib/python3.6/site-packages/qtoml/decoder.py", line 391, in parse_value
    raise TOMLDecodeError("can't parse type", p)
qtoml.decoder.TOMLDecodeError: can't parse type (line 1, column 4)
```

This is a clash between the current TOML specification and the way programming languages output numbers in scientific notation (see my bugreport https://github.com/toml-lang/toml/issues/356). qtoml should remove the trailing zero from exponentials.

**Comment by alethiophile** [comment]
Yup, that's a bug.

Got a test case and a tentative fix. Want to exercise it a bit more before committing it, since it's basically a hack.

**Comment by alethiophile** [comment]
I think this commit should fix it. I'll push a new version in a bit.
