### ISSUE TITLE
Dotted keys using string 'a.b.c' instead of dict a:{b:{c:'foo'}}}

### ISSUE THREAD

**Issue by C-Duv** [alethiophile/qtoml#5]
The TOML format allows dotted keys (["_Dotted keys are a sequence of bare or quoted keys joined with a dot._"](https://github.com/toml-lang/toml#keys)) but I fail to create one using this library.

I cannot reproduce the given TOML example code:

```Toml
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
```

Using Python dictionary:
```Python
{
    'name': "Orange",
    'physical.color': "orange",
    'physical.shape': "round",
    'site."google.com"': True,
}
```

### Reproduce code

```Python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import qtoml
import pprint

config = {
    'name': "Orange",
    'physical.color': "orange",
    'physical.shape': "round",
    'site."google.com"': True,
}

toml_string = qtoml.dumps(config)
print('TOML format:')
print(toml_string)

print('-----')

toml_loaded = qtoml.loads(toml_string)
pp = pprint.PrettyPrinter(indent=4)
print('Python dump:')
pp.pprint(toml_loaded)
```

Outputs:
```
TOML format:
name = 'Orange'
'physical.color' = 'orange'
'physical.shape' = 'round'
'site."google.com"' = true

-----
Python dump:
{   'name': 'Orange',
    'physical.color': 'orange',
    'physical.shape': 'round',
    'site."google.com"': True}
```

We can see the `physical` key is missing as we could expect from TOML format.

In order to get it, I must change the Python dictionary to:

```Python
config = {
    'name': "Orange",
    'physical': {
        'color': "orange",
        'shape': "round",
    },
    'site."google.com"': True,
}
```

Which outputs:
```
TOML format:
name = 'Orange'
'site."google.com"' = true

[physical]
color = 'orange'
shape = 'round'

-----
Python dump:
{   'name': 'Orange',
    'physical': {'color': 'orange', 'shape': 'round'},
    'site."google.com"': True}
```

Where `physical` key now exists (using the square bracket notation: which is fine).

Is dotted-notation supported (and I am doing something wrong)?

**Comment by alethiophile** [comment]
If the dictionary key itself has a dot in it, then this doesn't use the
TOML dotted-key notation, but simply embeds the dot in the key string (by
making it quoted). This is in accordance with the TOML spec.

Dotted keys correspond to nested dictionaries in the data structure. qTOML
will read these keys just fine, producing nested dictionaries as per the
spec; however, when encoding nested dictionaries, it doesn't ever write
dotted keys, but always uses the explicit square-bracket/separate-section
format. This was simply an arbitrary decision of mine; there are multiple
valid representations of these data structures, so I had to pick one.

I'm currently (slowly) working on a version upgrade which will provide more
control over generated output, if that's necessary.

**Comment by C-Duv** [comment]
I understand the decision (when trying to comply with 2 formats, you have to make a choice somewhere...): Thanks for the explanation.
