### ISSUE TITLE
Support for Python 2.7.X

### ISSUE THREAD

**Issue by LexiconCode** [alethiophile/qtoml#6]
Greetings, I know in 2020 support for Python 2.7.X will end. However projects still transitioning to Python 3. Currently "uiri/toml"  hhas some showstopping issues with incorrect string escaping in TOML encoder and serializer produced trailing whitespace. I understand of this is out of the scope of qtoml with your limited development time. In that case do you have another recommendation for a matured toml library for Python?

**Comment by alethiophile** [comment]
Adding support for an EOL'd Python version is not a huge priority at the moment. If someone wants to make a pull request for this I wouldn't necessarily object to merging it.
