### ISSUE TITLE
[feature request] Implement heterogeneous values in arrays as per the >0.5.0 (unreleased) TOML spec

### ISSUE THREAD

**Issue by miccoli** [alethiophile/qtoml#8]
The working and still unreleased TOML spec allows heterogenous values in arrays: see 
- TOML [CHANGELOG.md](https://github.com/toml-lang/toml/blob/606029cc8b5faa7b05c66c02729ba7beb8843259/CHANGELOG.md)
- TOML [README.md](https://github.com/toml-lang/toml/blob/68076ffc6d9a150d48f1df964551283542ad47bc/README.md#array)
- issue toml-lang/toml#665

This is a major improvement that better aligns TOML lists with python ones: I would suggest to implement this feature ahead of the formal release of the new TOML spec.

**Comment by alethiophile** [comment]
Agree this is a good idea. As best I can tell it should be trivial, just need to take out the explicit checks to forbid it. I'll work on it once I've got a moment.

**Comment by miccoli** [comment]
Code changes to the python code should be trivial, just a couple of lines to remove. What seems to me more complicated is adapting the unit tests to the new spec.

**Comment by alethiophile** [comment]
Now implemented in v0.3.0.
